import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sidebar } from "./components/Sidebar";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";
import MotionAnimatePresence from "./providers/MotionAnimatePresence";
import RecoilProvider from "./providers/RecoilProvider";
import { Header } from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Choruleta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <RecoilProvider>
        <html lang="pt-BR">
          <body
            className={[
              inter.className,
              "bg-neutral-900 text-white select-none relative max-h-screen h-full overflow-auto",
            ]
              .join(" ")
              .trimEnd()}
          >
            <Header.Root />

            <MotionAnimatePresence>
              <Sidebar.Root />
            </MotionAnimatePresence>
            {children}
          </body>
        </html>
      </RecoilProvider>
    </AuthProvider>
  );
}
